/**
 * Step 3 of the Preview runbook: parameterise the validator.
 *
 * Picks a seed UTxO from the funded deployer wallet (or --seed <txhash>#<ix>),
 * builds CoverParams from preview.config.json (oracle allowlist + quorum,
 * [ada, tUSDCx] tranches, product terms), applies them to plutus.json, and
 * cross-checks the script hash against `aiken blueprint apply`. Writes:
 *
 *   deployments/preview.json         addresses, policy id, params CBOR (public)
 *   deployments/preview.plutus.json  the applied blueprint (from aiken)
 *   deployments/preview.env          NEXT_PUBLIC_* values for apps/web
 *
 * With an unfunded deployer it runs as a dry run on a placeholder seed so the
 * pipeline is exercised end to end; the real hash depends on the real seed.
 */
import { execFileSync } from "node:child_process";
import { mkdtempSync, writeFileSync, copyFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { lpTokenName, type OutputReference } from "../../../../packages/sdk/src/cardano.ts";
import { assetId } from "../../../../packages/sdk/src/assets.ts";
import { buildParams, deployment, loadConfig } from "../lib/cover.ts";
import { DEPLOY_DIR, loadKey, sigPolicy } from "../lib/keys.ts";
import { previewLucid, readDeploymentFile, toJson, writeDeploymentFile } from "../lib/chain.ts";

const arg = (name: string) => {
  const i = process.argv.indexOf(`--${name}`);
  return i > 0 ? process.argv[i + 1] : undefined;
};

const cfg = loadConfig();
const file = readDeploymentFile();
const deployer = loadKey("deployer", "Preview");
const oracle = loadKey("oracle", "Preview");
const oraclePolicyId = cfg.oracle.policyId ?? sigPolicy(oracle.keyHash).policyId;
const usdcPolicyId = sigPolicy(deployer.keyHash).policyId;

let seed: OutputReference | undefined;
let dryRun = false;
const seedArg = arg("seed");
if (seedArg) {
  const [txHash, ix] = seedArg.split("#");
  seed = { txHash, outputIndex: Number(ix) };
} else if (!process.argv.includes("--offline")) {
  try {
    const lucid = await previewLucid();
    lucid.selectWallet.fromPrivateKey(deployer.privateKey);
    const utxos = await lucid.wallet().getUtxos();
    // Prefer a pure-ada UTxO so the seed is never a tUSDCx holding.
    const pick = utxos.find((u) => Object.keys(u.assets).length === 1) ?? utxos[0];
    if (pick) seed = { txHash: pick.txHash, outputIndex: pick.outputIndex };
  } catch (e) {
    console.warn(`could not query Preview (${(e as Error).message}); falling back to a dry run`);
  }
}
if (!seed) {
  dryRun = true;
  seed = { txHash: "00".repeat(32), outputIndex: 0 };
  console.log("deployer has no UTxOs yet: DRY RUN with a placeholder seed (00…00#0)");
}

const params = buildParams(cfg, seed, oraclePolicyId, usdcPolicyId);
const d = deployment("Preview", params);

// Independent check: aiken applies the same CBOR and must get the same hash.
let aikenMatches: boolean | undefined;
const appliedOut = join(DEPLOY_DIR, "deployments", dryRun ? "preview.dryrun.plutus.json" : "preview.plutus.json");
try {
  const tmp = join(mkdtempSync(join(tmpdir(), "ps-")), "applied.json");
  const cwd = join(DEPLOY_DIR, "..");
  execFileSync("aiken", ["blueprint", "apply", "-m", "cover", "-v", "cover", "-o", tmp, d.paramsCbor], { cwd, stdio: "pipe" });
  const hash = execFileSync("aiken", ["blueprint", "hash", "-i", tmp, "-m", "cover", "-v", "cover"], { cwd, stdio: "pipe" }).toString().trim();
  aikenMatches = hash === d.policyId;
  copyFileSync(tmp, appliedOut);
  console.log(`aiken blueprint hash ${hash} ${aikenMatches ? "== " : "!= "}lucid ${d.policyId}`);
  if (!aikenMatches) process.exitCode = 1;
} catch (e) {
  console.warn(`aiken not available for the cross-check: ${(e as Error).message.split("\n")[0]}`);
}

const out = {
  ...file,
  status: dryRun ? ("awaiting-funding" as const) : file.status === "initialised" ? file.status : ("planned" as const),
  generatedAt: new Date().toISOString(),
  assets: params.assets.map((a, i) => ({
    tranche: i,
    asset: assetId(a.asset),
    lpToken: d.policyId + lpTokenName(i),
    minPremium: a.minPremium.toString(),
  })),
  script: {
    hash: d.policyId,
    address: d.address,
    poolNft: d.poolNftUnit,
    paramsCbor: d.paramsCbor,
    seed: `${seed.txHash}#${seed.outputIndex}`,
    aikenApplyMatches: aikenMatches,
    ...(dryRun ? { dryRun: true } : {}),
  },
  params,
};
if (dryRun) {
  // Never overwrite a real plan with a dry run.
  writeFileSync(join(DEPLOY_DIR, "deployments", "preview.dryrun.json"), toJson(out));
} else writeDeploymentFile(out);

const env = [
  "# Generated by contracts/cardano/deploy `pnpm plan`. Public values only.",
  `NEXT_PUBLIC_CARDANO_NETWORK=preview`,
  `NEXT_PUBLIC_PREVIEW_SCRIPT_HASH=${d.policyId}`,
  `NEXT_PUBLIC_PREVIEW_POOL_ADDRESS=${d.address}`,
  `NEXT_PUBLIC_PREVIEW_POOL_NFT=${d.poolNftUnit}`,
  `NEXT_PUBLIC_PREVIEW_USDC_POLICY_ID=${usdcPolicyId}`,
  `NEXT_PUBLIC_PREVIEW_ORACLE_POLICY_ID=${oraclePolicyId}`,
  "",
].join("\n");
writeFileSync(join(DEPLOY_DIR, "deployments", dryRun ? "preview.dryrun.env" : "preview.env"), env);
console.log(toJson(out.script));
console.log(dryRun ? "wrote deployments/preview.dryrun.{json,env,plutus.json}" : "wrote deployments/preview.{json,env,plutus.json}; next: pnpm preview init");
