/**
 * Public facts about the live Cardano Preview deployment.
 * Source: contracts/cardano/deploy/deployments/preview.{json,env} (generated by `pnpm preview:plan`).
 * Every value here is public on-chain data; no keys.
 */
import type { AssetClass } from "@plutusshield/sdk/cardano";

export const PREVIEW = {
  network: "preview" as const,
  koios: process.env.NEXT_PUBLIC_PREVIEW_KOIOS ?? "https://preview.koios.rest/api/v1",
  explorer: "https://preview.cardanoscan.io",
  scriptHash: process.env.NEXT_PUBLIC_PREVIEW_SCRIPT_HASH ?? "4e5423fefc28871aef53bd2ee85722c19af742e6b7a99d507e0ce2ac",
  poolAddress:
    process.env.NEXT_PUBLIC_PREVIEW_POOL_ADDRESS ?? "addr_test1wp89ggl7ls5gwxh02w7ja6zhytqe4a6zu6m6n82s0cxw9tq4j5tgr",
  oraclePolicyId:
    process.env.NEXT_PUBLIC_PREVIEW_ORACLE_POLICY_ID ?? "d8365e107288ee8c1e313505cf2c754386eef7c95b2cd75b1fa1dd93",
  initTx: "fc2a3ca252051a41589f58b612e08427b512a2cf17e0b3fa5a53500f162ca236",
  /** Product max utilization the script is parameterised with (90%). */
  maxUtilizationBps: 9_000n,
  oracleQuorum: "2 of 3 feeds",
};

export interface PreviewAsset {
  asset: AssetClass;
  symbol: "ADA" | "USDC";
  ticker: string;
  decimals: number;
  lpToken: string;
}

const USDC_POLICY =
  process.env.NEXT_PUBLIC_PREVIEW_USDC_POLICY_ID ?? "e5c5ae166089e4d907cabf8456dea8aebb76a2d5c65458c8e1e632ef";

/** Tranche assets in `CoverParams.assets` order. */
export const PREVIEW_ASSETS: PreviewAsset[] = [
  { asset: { policyId: "", assetName: "" }, symbol: "ADA", ticker: "tADA", decimals: 6, lpToken: "lp00" },
  { asset: { policyId: USDC_POLICY, assetName: "745553444378" }, symbol: "USDC", ticker: "tUSDCx", decimals: 6, lpToken: "lp01" },
];

export const explorerTx = (hash: string) => `${PREVIEW.explorer}/transaction/${hash}`;
export const explorerAddress = (addr: string) => `${PREVIEW.explorer}/address/${addr}`;
